name: Run Pytest Unit Tests

on:
  push:
    branches:
      - main
      - ec2-experiments
    paths:
      - configs/**
      - src/**
      - tests/**
      - .github/**
      - Makefile
      - requirements.txt
      - pyproject.toml
      - poetry.lock
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
    paths:
      - configs/**
      - src/**
      - tests/**
      - .github/**
      - Makefile
      - requirements.txt
      - pyproject.toml
      - poetry.lock

jobs:
  reject-ec2:
    if: github.event_name == 'push' && github.ref != 'refs/heads/ec2-experiments'
    runs-on: ubuntu-latest
    steps:
      - name: Check if pushed by EC2 Deploy Key
        run: |
          AUTHOR_NAME=$(jq -r .pusher.name "$GITHUB_EVENT_PATH")
          AUTHOR_EMAIL=$(jq -r .pusher.email "$GITHUB_EVENT_PATH")

          echo "Commit by $AUTHOR_NAME <$AUTHOR_EMAIL>"

          if [[ "$AUTHOR_NAME" == "ec2-deploy-bot" ]] || [[ "$AUTHOR_EMAIL" == "ec2@myinfra.local" ]]; then
            echo "Blocked deploy key push to main."
            exit 1
          fi

          echo "Push allowed."
  unit-tests:
    # if: (github.event_name == 'push' || github.event_name == 'pull_request') && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}/src
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.11.7
        uses: actions/setup-python@v5
        with:
          python-version: 3.11.7

      - name: Install make
        run: |
          sudo apt-get update && sudo apt-get install -y make

      - name: Create .venv environment
        run: |
          make init
          make install

      - name: Lint check
        run: |
          make lint-check
        continue-on-error: true

      - name: Type check
        run: |
          make type-check
        continue-on-error: true

      - name: Run pytest with coverage
        run: |
          make unit-tests