name: Run Pytest Unit Tests

env:
  PYTHONPATH: src

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.11.4
        uses: actions/setup-python@v5
        with:
          python-version: 3.11.4

      - name: Install make
        run: |
          sudo apt-get update && sudo apt-get install -y make

      - name: Create .venv environment
        run: |
          make init
          make install

      - name: Run pytest with coverage
        run: |
          . .venv/bin/activate && pytest --cov=. --cov-report=term --cov-report=html tests/
